spring:

  datasource:
    url: jdbc:mysql://192.168.199.128:3306/stock_example?characterEncoding=utf-8
    username: mydb
    password: 1234
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/stock_example?characterEncoding=utf-8
#    username: springetc
#    password: springetc12#

  redis:
    host: 192.168.199.128
    port: 6379
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    open-in-view: false
    database: MYSQL
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
