spring:


  profiles:
    active: window

# app-name
  application:
    name: user-app

# security
#  security:
#    user:
#      name: user
#      password: 1234

# jpa
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    open-in-view: false
    database: MYSQL
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # log
  logging:
    level:
      org.springframework: info