# MariaDB Connection
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1/mydb?useUnicode=true&characterEncoding=utf-8
    username: myuser
    password: 1234